---
- name: Adding hosts to /etc/hosts
  lineinfile:
       path: /etc/hosts
       line: "{{ item.ip }} {{ item.name }}.sap.x5.ru {{ item.name }}  #EDITED on {{ ansible_date_time.date }}"
       state: present
  loop: "{{ add_hosts }}"

- name: Removing (by comment out) hosts from /etc/hosts
  lineinfile:
       path: /etc/hosts
       regexp: '{{ item.ip }}(\s+){{ item.name }}.sap.x5.ru(\s+){{ item.name }}'
       state: present
       line: "## {{ item.name }} {{ item.ip }} REMOVED on {{ ansible_date_time.date }} ##"
  loop: '{{ del_hosts }}'
