---
- name: Copy splunk rpm
  copy:
    src: /share/pub/Distr/splunk/splunkforwarder-8.1.3-63079c59e632-linux-2.6-x86_64.rpm
    dest: /tmp/splunkforwarder-8.1.3-63079c59e632-linux-2.6-x86_64.rpm

- name: Install splunk agent
  yum:
    name: /tmp/splunkforwarder-8.1.3-63079c59e632-linux-2.6-x86_64.rpm
    state: present

- name: Stop splunk
  raw: "/opt/splunkforwarder/bin/splunk stop"
  ignore_errors: true

- name: Enable boot-start
  raw: '/opt/splunkforwarder/bin/splunk enable boot-start -user root --accept-license --answer-yes --no-prompt'

- name: Add user admin
  raw: "/opt/splunkforwarder/bin/splunk add user {{ splunk_user }} -password {{ splunk_password }} -role admin"
  ignore_errors: true

- name: Set splunk port
  raw: "/opt/splunkforwarder/bin/splunk set splunkd-port {{ splunk_agent_port }}"
  ignore_errors: true

- name: Set splunk server
  raw: "/opt/splunkforwarder/bin/splunk set deploy-poll {{ splunk_server }}:{{ splunk_server_port }}"
  ignore_errors: true

- name: Start splunk
  raw: "/opt/splunkforwarder/bin/splunk start"


