---
zabbix_server_1: 192.168.58.79
zabbix_server_2: 192.168.58.80
zabbix_host_metadata: gc8QMPRur66E9leR
zabbix_host_hardware: "Power"
zabbix_host_os: "AIX"
zabbix_host_app: "Unknown"
zabbix_host_subapp: "Unknown"
zabbix_host_env: "Unknown"
